import type { IllustrationProps } from './index';

export default function CodeBlockIllustration({
  transparent = false,
  ...props
}: IllustrationProps) {
  return transparent ? (
    <svg
      width="200"
      height="95"
      viewBox="0 0 200 95"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      {...props}
    >
      <rect
        x="1.5"
        y="1.5"
        width="197"
        height="92"
        rx="6.5"
        stroke="var(--illustration-primary)"
        strokeWidth="3"
      />
      <rect
        x="16"
        y="16"
        width="40"
        height="3"
        fill="var(--illustration-primary)"
      />
      <rect
        x="16"
        y="76"
        width="20"
        height="3"
        fill="var(--illustration-primary)"
      />
      <rect
        x="32"
        y="31"
        width="60"
        height="3"
        fill="var(--illustration-secondary)"
      />
      <rect
        x="32"
        y="46"
        width="30"
        height="3"
        fill="var(--illustration-secondary)"
      />
      <rect
        x="32"
        y="61"
        width="40"
        height="3"
        fill="var(--illustration-secondary)"
      />
      <rect
        x="76"
        y="61"
        width="50"
        height="3"
        fill="var(--illustration-secondary)"
      />
      <rect
        x="66"
        y="46"
        width="30"
        height="3"
        fill="var(--illustration-primary)"
      />
      <rect
        x="130"
        y="61"
        width="50"
        height="3"
        fill="var(--illustration-primary)"
      />
      <rect
        x="100"
        y="46"
        width="50"
        height="3"
        fill="var(--illustration-primary)"
      />
      <rect
        x="96"
        y="31"
        width="46"
        height="3"
        fill="var(--illustration-primary)"
      />
      <rect
        x="146"
        y="31"
        width="30"
        height="3"
        fill="var(--illustration-primary)"
      />
    </svg>
  ) : (
    <svg
      width="200"
      height="95"
      viewBox="0 0 200 95"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      {...props}
    >
      <rect
        x="1.5"
        y="1.5"
        width="197"
        height="92"
        rx="6.5"
        fill="var(--bg-default)"
        stroke="var(--illustration-primary)"
        strokeWidth="3"
      />
      <rect
        x="16"
        y="16"
        width="40"
        height="3"
        fill="var(--illustration-primary)"
      />
      <rect
        x="16"
        y="76"
        width="20"
        height="3"
        fill="var(--illustration-primary)"
      />
      <rect
        x="32"
        y="31"
        width="60"
        height="3"
        fill="var(--illustration-secondary)"
      />
      <rect
        x="32"
        y="46"
        width="30"
        height="3"
        fill="var(--illustration-secondary)"
      />
      <rect
        x="32"
        y="61"
        width="40"
        height="3"
        fill="var(--illustration-secondary)"
      />
      <rect
        x="76"
        y="61"
        width="50"
        height="3"
        fill="var(--illustration-secondary)"
      />
      <rect
        x="66"
        y="46"
        width="30"
        height="3"
        fill="var(--illustration-primary)"
      />
      <rect
        x="130"
        y="61"
        width="50"
        height="3"
        fill="var(--illustration-primary)"
      />
      <rect
        x="100"
        y="46"
        width="50"
        height="3"
        fill="var(--illustration-primary)"
      />
      <rect
        x="96"
        y="31"
        width="46"
        height="3"
        fill="var(--illustration-primary)"
      />
      <rect
        x="146"
        y="31"
        width="30"
        height="3"
        fill="var(--illustration-primary)"
      />
    </svg>
  );
}
